### ISSUE TITLE
strtr is a better way to replace strings in Line 122

### ISSUE THREAD

**Issue by stenote** [top-think/framework#47]
https://github.com/top-think/framework/blob/master/library/think/View.php#L122

修改为如下，更清晰，效率更高

```
$content = strtr($content, $this->replace);
```

ref:

* http://stackoverflow.com/questions/8177296/when-to-use-strtr-vs-str-replace

**Comment by hugtale** [comment]
下面不是也有人写了两个 difference 了吗？两个用法上还是有区别的。尤其是第一个 difference，就决定了不能用 strtr

**Comment by stenote** [comment]
@hugtale 哪里？

```
stenote@vps:/path-to-thinkphp/thinkphp$ grep -rn 'difference' ./ |wc -l
0
```

没有 grep 出来啊

**Comment by hugtale** [comment]
First difference:
=

An interesting example of a different behaviour between strtr and str_replace is in the comments section of the PHP Manual:

~~~
<?php
$arrFrom = array("1","2","3","B");
$arrTo = array("A","B","C","D");
$word = "ZBB2";
echo str_replace($arrFrom, $arrTo, $word);
?>
~~~
I would expect as result: "ZDDB"
However, this return: "ZDDD" (Because B = D according to our array)
To make this work, use "strtr" instead:

~~~
<?php
$arr = array("1" => "A","2" => "B","3" => "C","B" => "D");
$word = "ZBB2";
echo strtr($word,$arr);
?>
~~~
This returns: "ZDDB"
This means that str_replace is a more global approach to replacements, while strtr simply translates the chars one by one.

Another difference:
=

Given the following code (taken from PHP String Replacement Speed Comparison):

~~~
<?php
$text = "PHP: Hypertext Preprocessor";

$text_strtr = strtr($text
    , array("PHP" => "PHP: Hypertext Preprocessor"
        , "PHP: Hypertext Preprocessor" => "PHP"));
$text_str_replace = str_replace(array("PHP", "PHP: Hypertext Preprocessor")
    , array("PHP: Hypertext Preprocessor", "PHP")
    , $text);
var_dump($text_strtr);
var_dump($text_str_replace);
?>
~~~
The resulting lines of text will be:

~~~
string(3) "PHP"
string(27) "PHP: Hypertext Preprocessor"
~~~

**Comment by hugtale** [comment]
好像就是替换顺序变了？str_replace是从前往后替换，strtr是从后往前替换？

**Comment by stenote** [comment]
这个地方看场景，哪个更适合呢？

假设，A 需要替换为 B， B 需要替换为 C，

那么 AB 变为 BC，还是 AB 变为 CC ？

**Comment by liu21st** [comment]
感谢反馈 已经采纳~
